/**
 * Even Fibonacci numbers
 * Problem 2
 * Each new term in the Fibonacci sequence is 
 * generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence 
 * whose values do not exceed four million, find the 
 * sum of the even-valued terms.
 * @author Isaac Assegai
 */
public class Problem2 {
	public static void main(String [] args){
		int limit = 4000000;
		int sum = 2;
		int val = 0;
		int first = 1;
		int second = 2;
		do{
			val = first + second;
			first = second;
			second = val;
			if(val % 2 == 0 && val < limit){
				sum += val;
			}
		}while(val <= limit);
		System.out.println("Answer: " + sum);
	}
}
